## Worksheet 2


### Data Structures (List, Set, Dictionary, and Numpy Array)

### Due on 5/25/22 @ 11:55 pm EST (see Assignment Folder in Sakai)

## Authorized help and collaboration rules

You **may not** collaborate with friends or teammates. You **may** use your notes, class provided resources (e.g., web links, notebooks,videos, slides) to help you solve the problems below. For effective learning, you should try to complete the worksheet on your own before looking for help. 

If you have any questions regarding what is, or is not, authorized you must ask. Saying after the fact you didn't understand, or were not sure, is not a valid excuse.

## Honor pledge

I pledge the COMP 116 honor code.

To the acknowledgethe **authororized help and collaboration rules** please edit the Markdown below and enter the requested information.

```
Onyen = mllandon
Author = Matthew Landon
PID = 730461081
```

## Python version check

After running the next cell you should be running Python version `3.7.0` or later.

In [1]:
import sys
print(sys.version)

3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]


*****

### Question 1: List Data Structure [6 Points Total]

In each coding cell write the solution and then **print** the elements in **q1_list**. In total, there will be **ten** print statements, i.e., one print for each question part. **Note**: print statement does not need to be formatted. 

Documentation:
- <a href="https://www.w3schools.com/python/python_lists.asp">Syntax</a>
- <a href="https://www.w3schools.com/python/python_lists_methods.asp">Operations</a>

Part 1 [0.5 pt]: Create a new list named **q1_list** that is empty (i.e., no elements).

In [39]:
# Solution to Part 1

q1_list = []

Part 2 [1 pt]: Add the following elements to **q1_list** in the order specified below:
- integer **42**     
- float **3.14** 
- string **comp116**
- string **the matrix**
- Boolean **True** 

In [40]:
# Solution to Part 2

listaddons = [42, 3.14, "comp116", "the matrix", True]
q1_list.extend(listaddons)
print(q1_list)

[42, 3.14, 'comp116', 'the matrix', True]


Part 3 [0.5 pt]: Remove the following elements from **q1_list**.
- **comp116**
- **the matrix**

In [11]:
# Solution to Part 3
q1_list.remove("comp116")
q1_list.remove("the matrix")
print(q1_list)

[42, 3.14, True]


Part 4 [1 pt]: Insert the following elements in **q1_list** at the specified positions.
- Position 1, integer **-1**
- Position 0, float **-10.25**
- Position 2, float **42.0**


In [12]:
# Solution to Part 4
q1_list.insert(0, -10.25)
q1_list.insert(1, -1)
q1_list.insert(2, 42.0)
print(q1_list)

[-10.25, -1, 42.0, 42, 3.14, True]


Part 5 [0.5 pt]: Append the following elements to **q1_list** in the order specified below.
- integer **-100**
- integer **116**
- float **47.47**   


In [13]:
# Solution to Part 5

q1_list.append(-100)
q1_list.append(116)
q1_list.append(47.47)
print(q1_list)

[-10.25, -1, 42.0, 42, 3.14, True, -100, 116, 47.47]


Part 6 [0.5 pt]: Reverse the order of the elements in **q1_list**.


In [14]:
# Solution to Part 6
import numpy as np

q1_flipped_list = np.flip(q1_list)
q1_list[::-1]
print(q1_list[::-1])

[47.47, 116, -100, True, 3.14, 42, 42.0, -1, -10.25]


Part 7 [0.5 pt]: Sort the elements in **q1_list** in ascending order (i.e., element with the smallest value is at position 0 in the list, and element with the largest value is at the very last position in the list). 


In [15]:
# Solution to Part 7

q1_list.sort()
print(q1_list)

[-100, -10.25, -1, True, 3.14, 42.0, 42, 47.47, 116]


Part 8 [0.5 pt]: Sort the elements in **q1_list** in descending order (i.e., element with the largest value is at position 0 in the list, and element with the smallest value is at the very last position in the list). 

In [16]:
# Solution to Part 8

q1_list.sort(reverse=True)
print(q1_list)

[116, 47.47, 42.0, 42, 3.14, True, -1, -10.25, -100]


Part 9 [0.5 pt]: Create a variable named **q1_position** that holds the position of element **116** in **q1_list** (Hint: <a href="https://www.w3schools.com/python/ref_list_index.asp">index</a>).


In [17]:
# Solution too Part 9

q1_position = q1_list.index(116)
print(q1_position)

0


Part 10 [0.5 pt]: Remove all the elements in **q1_list** (i.e., empty list).

In [21]:
# Solution to Part 10

q1_list.clear()

****

****

### Question 2 : Set Data Structure [5 Points Total]

In each coding cell write the solution and then **print** the elements in the appropriate set variable. In total, there will be **seven** print statements, i.e., one print for each question part. **Note**: print statement does not need to be formatted. 

Documenation:
- <a href="https://www.w3schools.com/python/python_sets.asp">Syntax</a>
- <a href="https://www.w3schools.com/python/python_sets_methods.asp">Operations</a>

Part 1 [0.5 pt]: Create a set named **q2_set_a** that is empty (i.e., zero elements).

In [94]:
# Solution to Part 1

q2_set_a = set()
print(q2_set_a)
print(len(q2_set_a))

set()
0


Part 2 [1 pt]: Add the following elements to **q1_set_a** (remember, order is not important).
- integer **42**     
- float **3.14** 
- string **comp116**
- string **the matrix**
- Boolean **True** 

In [95]:
# Solution to Part 2

setaddon = {42,3.14,"comp116","the matrix", True}
q2_set_a.update(setaddon)
print(q2_set_a)

{True, 3.14, 'the matrix', 42, 'comp116'}


Part 3 [0.5 pt]: Remove the following elements from **q2_set_a**.
- **comp116**
- **the matrix**

In [96]:
# Solution to Part 3

q2_set_a.remove("comp116")
q2_set_a.remove("the matrix")
print(q2_set_a)

{True, 3.14, 42}


Part 4 [0.5 pt]: Create a set named **q2_set_b** that is intialized with the following elements:
- integer **-1**
- float **-10.25**
- float **42.0**

In [97]:
# Solution to Part 4

q2_set_b = {-1,-10.25,42.0}

Part 5 [1 pt]: Crete a set named **q2_intersection** that includes values that are in both sets, i.e., the intersection $a \cap b$.  


In [98]:
# Solution to Part 5

q2_intersection = q2_set_a.intersection(q2_set_b)
print(q2_intersection)

{42.0}


Part 6 [1 pt]: Crete a set named **q2_union** that includes values that are in either set, i.e., the union $a \cup b$.  

In [55]:
# Solution to Part 6

q2_union = q2_set_a.union(q2_set_b)
print(q2_union)

{True, 3.14, -10.25, 42, -1}


Part 7 [0.5 pt]: Remove all elements in **q2_set_a** (i.e., empty set) 

In [56]:
# Solution to Part 7

q2_set_a.clear()
print(q2_set_a)

set()


****

*****

### Question 3: Dictionary Data Structure [5 Points Total]

In each coding cell write the solution and then **print** the elements in **q3_dict**. In total, there will be **seven** print statements, i.e., one print for each question part. **Note**: print statement does not need to be formatted. 

Documentation:
- <a href="https://www.w3schools.com/python/python_dictionaries.asp">Syntax</a>
- <a href="https://www.w3schools.com/python/python_dictionaries_methods.asp">Operations</a>

Part 1 [0.5 pt]: Create a dictionary named **q3_dict** that is initially empty (i.e., zero key-value pairs)

In [32]:
# Solution to Part 1

q3_dict = {}


Part 2 [1 pt]: Add the following key-value pairs to **q3_dict** (data types are defined in the parentheses).
- Key **first_name** (string) with value **Keanu** (string)   
- Key **last_name** (string) with value **Reeves** (string)
- Key **age** (string) with value **56** (integer)
- Key **year** (string) with value **1999** (integer)
- Key **famous_qoute** (string) with value **I know kung-fu** (string)
- Key **favorite_number** (string) with value **42** (integer)
- Key **co_star** (string) with value **Morpheus** (string)


In [33]:
# Solution to Part 2
q3_dict = dict()
q3_dict["first_name"] = "Keanu"
q3_dict["last_name"] = "Reeves"
q3_dict["age"] = 56
q3_dict["year"] = 1999
q3_dict["famous_quote"] = "I know kung-fu"
q3_dict["favorite_number"] = 42
q3_dict["co_star"] = "Morpheus"

print(q3_dict)

{'first_name': 'Keanu', 'last_name': 'Reeves', 'age': 56, 'year': 1999, 'famous_quote': 'I know kung-fu', 'favorite_number': 42, 'co_star': 'Morpheus'}


Part 3 [0.5 pt]: Remove the following keys (and associated values) from **q3_dict**.
- **year**
- **favorite_number**

In [34]:
# Solution to Part 3

q3_dict.pop("year")
q3_dict.pop("favorite_number")
print(q3_dict)

{'first_name': 'Keanu', 'last_name': 'Reeves', 'age': 56, 'famous_quote': 'I know kung-fu', 'co_star': 'Morpheus'}


Part 4 [1 pt]: For the **q3_dict** keys update their values as specified below.
- **famous_qoute** with **We need guns. Lots of guns** (string)
- **co_star** with **Trinity** (string)

In [35]:
# Solution to Part 4

q3_dict.update({"famous_quote":"We need guns. Lots of guns"})
q3_dict.update({"co_star":"Trinity"})
print(q3_dict)

{'first_name': 'Keanu', 'last_name': 'Reeves', 'age': 56, 'famous_quote': 'We need guns. Lots of guns', 'co_star': 'Trinity'}


Part 5 [0.5 pt]: Add the key-value pair to **q3_dict** (data types are defined in the parentheses).
- Key **year** (string) with value **1999** (integer)


In [36]:
# Solution to Part 5

q3_dict.update({"year": 1999})
print(q3_dict)

{'first_name': 'Keanu', 'last_name': 'Reeves', 'age': 56, 'famous_quote': 'We need guns. Lots of guns', 'co_star': 'Trinity', 'year': 1999}


Part 6 [1 pt]: Create a new **list** data structure named **keys_list** that includes each key in **q3_dict**. (Hint: <a href="https://www.w3schools.com/python/ref_dictionary_keys.asp">keys()</a>).

In [37]:
# Solution to Part 6

keys_list = q3_dict.keys()
print(keys_list)

dict_keys(['first_name', 'last_name', 'age', 'famous_quote', 'co_star', 'year'])


Part 7 [0.5 pt]: Remove all the key-value pairs in **q3_dict** (i.e., empty dictionary) 

In [38]:
# Solution to Part 7

q3_dict.clear()
print(q3_dict)

{}


***

****
### Question 4: Numpy Array Data Structure [4 Points Total]

In each coding cell write the solution and then **print** the elements in **q4_array**. In total, there will be **six** print statements, i.e., one print for each question part. **Note**: print statement does not need to be formatted. 

Documentation:
- <a href="https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp">W3School</a>
- <a href="https://numpy.org/doc/stable/reference/generated/numpy.array.html">Reference</a>
- <a href="https://numpy.org/doc/stable/reference/routines.math.html#">Math operations</a>
- <a href="https://numpy.org/doc/stable/reference/routines.sort.html">Search and Sort</a>

Part 1 [0.5 pt]: Create a 1D numpy array named **q4_array** that stores five integers that are initially set to zero.




In [2]:
# Solution to Part 1

import numpy as np

q4_array = np.array([0,0,0,0,0])
print(q4_array)

[0 0 0 0 0]


Part 2 [1 pt]: Update the value at the following positions in **q4_array**:
- position 3 to **100**
- position 0 to **200**
- position 1 to **-10**
- position 2 to **15**
- position 4 to **-42**


In [3]:
# Solution to Part 2

q4_array[3] = 100
q4_array[0] = 200
q4_array[1] = -10
q4_array[2] = 15
q4_array[4] = -42
print(q4_array)

[200 -10  15 100 -42]


Part 3 [0.5 pt]: Update the values in **q4_array** at the following positions.
- position 1 to **-20** 
- position 0 to **20**

In [4]:
# Solution to Part 3

q4_array[1] = -20
q4_array[0] = 20
print(q4_array)

[ 20 -20  15 100 -42]


Part 4 [1 pt]: Reverse the order of the values in **q4_array** (Hint: <a href="https://numpy.org/doc/stable/reference/generated/numpy.flip.html">flip</a>).


In [5]:
# Solution to Part 4

q4_flipped = np.flip(q4_array)
q4_array[::-1]
print(q4_array[::-1])

[-42 100  15 -20  20]


Part 5 [0.5 pt]: Sort the values in **q4_array** in ascending order.


In [6]:
# Solution to Part 5
q4_array_ascending = np.sort(q4_array)
print(q4_array_ascending)

[-42 -20  15  20 100]


Part 6 [0.5 pt]: Sort the values in **q4_array** in decending order.

In [7]:
# Solution to Part 6

q4_array_descending = q4_array_ascending[::-1]
print(q4_array_descending)

[100  20  15 -20 -42]
